### ISSUE TITLE
Get tests running with github actions. 

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/SugarSpice#4]
Tests are pretty empty right now as they are mostly used to testing things locally. But it still valuable to get deployments going for when tests begin to be written properly sooner that later.

**Comment by AustinSanders** [comment]
@Kelvinrr This should be closable as of #8, but I don't have permissions to close issues on this repo for some reason.

**Comment by Kelvinrr** [comment]
@AustinSanders Yeah, I think you're not part of the org or something for whatever reason? I'll double check what's going on in the AM
