### ISSUE TITLE
ghc::filesystem includes causing conflicts with other headers

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/SugarSpice#50]
We ran into an issue where including the headers that re-implement std::filesystem caused compilation errors in Fixtures.h as the compiler attempted to resolve the system headers before the ghc headers. We want the reverse to be true. 

I believe this is because the ghc headers tries to dynamically load the std::filesystem implementation before it's own implementation as a fallback which may be having side affects with other header only libs. 

This is also a problem as it munges the namespace for anyone including our headers. 

see the README on their repo: https://github.com/gulrak/filesystem

A possible solution is to just replace `#include <ghc/fs_std.hpp>` which is doing the namespace munging with `#include <ghc/fs_std_fwd.hpp>` in our headers and `#include <ghc/fs_std_impl.cpp>` in our source.  If I understand the docs correctly, this should properly forward declare a std::fs style API for headers and implement them in the .cpp which dynamic switching between standard implementations and the GHC implementation without namespace munging.

**Comment by Kelvinrr** [comment]
probably can be solved by #83

**Comment by jessemapel** [comment]
@Kelvinrr Is there a good way to re-produce this? I want to test if it's fixed on not in #87

**Comment by Kelvinrr** [comment]
I think @scsides might have some insight on how to reproduce, he originally ran into the compile errors trying to build tests.

**Comment by scsides** [comment]
I don't have anything specific. It's been tool long.
