### ISSUE TITLE
Flags to enable/disable features in CMAKE

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/SugarSpice#72]
The CMake configuration kinda just builds everything. We should update it so that the library, docs and tests can be disabled or enabled and default to enabled.

**Comment by jessemapel** [comment]
This was done in 98740ff35de93306ec940578c6711d22b43ed355. Flags are `SUGARSPICE_BUILD_DOCS` and `SUGARSPICE_BUILD_TESTS`.
